const ADD_TASK = 'ADD_TASK';
const REMOVE_TASK = 'REMOVE_TASK';
const COMPLETE_TASK = 'COMPLETE_TASK';
const UPDATE_TASK = 'UPDATE_TASK';
const GET_ALL = 'GET_ALL';
const TASK_ERROR = 'TASK_ERROR';
const TASK_LOADING = 'TASK_LOADING';

export {
  ADD_TASK,
  REMOVE_TASK,
  COMPLETE_TASK,
  UPDATE_TASK,
  GET_ALL,
  TASK_LOADING,
  TASK_ERROR,
};
